name: Gitlab Client Build

on:  
  push:
    paths: [ "projects/gitlab-client/**" ]
  pull_request:
    paths: [ "projects/gitlab-client/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build gitlab-client
    - run: npm run test gitlab-client
